# Generated by Django 4.2 on 2026-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], db_index=True, default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(0, '讲座'), (1, '比赛'), (2, '晚会')], db_index=True, verbose_name='活动类型'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', '-created_at'], name='activities__status_cbfc90_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['type', 'status'], name='activities__type_40a4f0_idx'),
        ),
    ]
