# Generated by Django 4.2 on 2026-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_created_at_alter_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(0, '讲座'), (1, '比赛'), (2, '晚会')], verbose_name='活动类型'),
        ),
    ]
