# Generated by Django 4.2 on 2026-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否被删除'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['activity', 'is_deleted', '-created_at'], name='comments_co_activit_e06421_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='comments_co_user_id_4d6386_idx'),
        ),
    ]
