# Generated by Django 4.2 on 2026-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='poster',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='活动海报URL'),
        ),
    ]
